project:
  type: website

website:
  title: "Quarto Website 2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
site_dir: "docs"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

